# Generated by Django 3.2.21 on 2023-09-22 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtGroupCode', models.CharField(max_length=20)),
                ('txtGroupName', models.CharField(max_length=200)),
                ('dteCreated', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
