# Generated by Django 3.2.21 on 2023-09-22 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dteCreated', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('txtUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('txtUserAccessGroup', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usergroup')),
            ],
        ),
    ]
